# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Distplot.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(729, 444)
        self.gridLayout_3 = QtGui.QGridLayout(Dialog)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.filePath = QtGui.QLineEdit(Dialog)
        self.filePath.setReadOnly(True)
        self.filePath.setPlaceholderText(_fromUtf8(""))
        self.filePath.setObjectName(_fromUtf8("filePath"))
        self.gridLayout_3.addWidget(self.filePath, 3, 2, 1, 1)
        self.browseButton = QtGui.QToolButton(Dialog)
        self.browseButton.setObjectName(_fromUtf8("browseButton"))
        self.gridLayout_3.addWidget(self.browseButton, 3, 3, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_3.addWidget(self.buttonBox, 4, 2, 1, 2)
        self.deleteTrace = QtGui.QPushButton(Dialog)
        self.deleteTrace.setObjectName(_fromUtf8("deleteTrace"))
        self.gridLayout_3.addWidget(self.deleteTrace, 1, 1, 1, 1)
        self.traceTable = QtGui.QTableWidget(Dialog)
        self.traceTable.setEnabled(True)
        self.traceTable.setObjectName(_fromUtf8("traceTable"))
        self.traceTable.setColumnCount(4)
        self.traceTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.traceTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.traceTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.traceTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.traceTable.setHorizontalHeaderItem(3, item)
        self.gridLayout_3.addWidget(self.traceTable, 2, 0, 1, 4)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.expField1 = gui.QgsFieldExpressionWidget(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.expField1.sizePolicy().hasHeightForWidth())
        self.expField1.setSizePolicy(sizePolicy)
        self.expField1.setObjectName(_fromUtf8("expField1"))
        self.gridLayout.addWidget(self.expField1, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.colorButton = gui.QgsColorButtonV2(self.tab)
        self.colorButton.setObjectName(_fromUtf8("colorButton"))
        self.gridLayout.addWidget(self.colorButton, 0, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.LayerCombo = gui.QgsMapLayerComboBox(self.tab)
        self.LayerCombo.setObjectName(_fromUtf8("LayerCombo"))
        self.gridLayout.addWidget(self.LayerCombo, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.tab)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(250, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem1, 1, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 0, 1, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.curveCombo = QtGui.QComboBox(self.tab_2)
        self.curveCombo.setObjectName(_fromUtf8("curveCombo"))
        self.curveCombo.addItem(_fromUtf8(""))
        self.curveCombo.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.curveCombo, 1, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.tab_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_4.addWidget(self.label_3, 1, 1, 1, 1)
        self.rugCheck = QtGui.QCheckBox(self.tab_2)
        self.rugCheck.setChecked(True)
        self.rugCheck.setObjectName(_fromUtf8("rugCheck"))
        self.gridLayout_4.addWidget(self.rugCheck, 0, 1, 1, 1)
        self.curveCheck = QtGui.QCheckBox(self.tab_2)
        self.curveCheck.setChecked(True)
        self.curveCheck.setObjectName(_fromUtf8("curveCheck"))
        self.gridLayout_4.addWidget(self.curveCheck, 0, 3, 1, 1)
        self.histCheck = QtGui.QCheckBox(self.tab_2)
        self.histCheck.setChecked(True)
        self.histCheck.setObjectName(_fromUtf8("histCheck"))
        self.gridLayout_4.addWidget(self.histCheck, 0, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.tab_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_4.addWidget(self.label_4, 2, 1, 1, 1)
        self.binSize = QtGui.QDoubleSpinBox(self.tab_2)
        self.binSize.setMinimum(0.1)
        self.binSize.setMaximum(3.0)
        self.binSize.setSingleStep(0.1)
        self.binSize.setProperty("value", 0.5)
        self.binSize.setObjectName(_fromUtf8("binSize"))
        self.gridLayout_4.addWidget(self.binSize, 2, 2, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 4)
        self.addTrace = QtGui.QPushButton(Dialog)
        self.addTrace.setObjectName(_fromUtf8("addTrace"))
        self.gridLayout_3.addWidget(self.addTrace, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.LayerCombo, QtCore.SIGNAL(_fromUtf8("layerChanged(QgsMapLayer*)")), self.expField1.setLayer)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.filePath.setText(_translate("Dialog", "Temporary file", None))
        self.browseButton.setText(_translate("Dialog", "...", None))
        self.deleteTrace.setText(_translate("Dialog", "Delete Trace", None))
        item = self.traceTable.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Trace ID", None))
        item = self.traceTable.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Layer", None))
        item = self.traceTable.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Field", None))
        item = self.traceTable.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Color", None))
        self.label_2.setText(_translate("Dialog", "Field", None))
        self.label_5.setText(_translate("Dialog", "Color", None))
        self.label.setText(_translate("Dialog", "Layer", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Plot Settings", None))
        self.curveCombo.setItemText(0, _translate("Dialog", "kde", None))
        self.curveCombo.setItemText(1, _translate("Dialog", "normal", None))
        self.label_3.setText(_translate("Dialog", "Curve Type", None))
        self.rugCheck.setText(_translate("Dialog", "Show Rug", None))
        self.curveCheck.setText(_translate("Dialog", "Show Curve", None))
        self.histCheck.setText(_translate("Dialog", "Show Histogram", None))
        self.label_4.setText(_translate("Dialog", "Bin Size", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Layout Customization (optional)", None))
        self.addTrace.setText(_translate("Dialog", "Add Trace", None))

from qgis import gui
