# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Histogram.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(763, 501)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(400, 450, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.filePath = QtGui.QLineEdit(Dialog)
        self.filePath.setGeometry(QtCore.QRect(208, 405, 504, 33))
        self.filePath.setReadOnly(True)
        self.filePath.setPlaceholderText(_fromUtf8(""))
        self.filePath.setObjectName(_fromUtf8("filePath"))
        self.addTrace = QtGui.QPushButton(Dialog)
        self.addTrace.setGeometry(QtCore.QRect(10, 173, 85, 31))
        self.addTrace.setObjectName(_fromUtf8("addTrace"))
        self.browseButton = QtGui.QToolButton(Dialog)
        self.browseButton.setGeometry(QtCore.QRect(718, 407, 26, 29))
        self.browseButton.setObjectName(_fromUtf8("browseButton"))
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(10, 6, 734, 161))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.label = QtGui.QLabel(self.tab)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.LayerCombo = gui.QgsMapLayerComboBox(self.tab)
        self.LayerCombo.setObjectName(_fromUtf8("LayerCombo"))
        self.gridLayout.addWidget(self.LayerCombo, 0, 1, 1, 1)
        self.expField1 = gui.QgsFieldExpressionWidget(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.expField1.sizePolicy().hasHeightForWidth())
        self.expField1.setSizePolicy(sizePolicy)
        self.expField1.setObjectName(_fromUtf8("expField1"))
        self.gridLayout.addWidget(self.expField1, 1, 1, 1, 1)
        self.colorButton = gui.QgsColorButtonV2(self.tab)
        self.colorButton.setObjectName(_fromUtf8("colorButton"))
        self.gridLayout.addWidget(self.colorButton, 0, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 1, 2, 1, 1)
        self.alpha = QtGui.QSlider(self.tab)
        self.alpha.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.alpha.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.alpha.setMinimum(0)
        self.alpha.setMaximum(100)
        self.alpha.setSingleStep(1)
        self.alpha.setProperty("value", 1)
        self.alpha.setOrientation(QtCore.Qt.Horizontal)
        self.alpha.setInvertedAppearance(False)
        self.alpha.setInvertedControls(False)
        self.alpha.setTickPosition(QtGui.QSlider.TicksAbove)
        self.alpha.setTickInterval(10)
        self.alpha.setObjectName(_fromUtf8("alpha"))
        self.gridLayout.addWidget(self.alpha, 1, 3, 1, 1)
        self.alphaBox = QtGui.QSpinBox(self.tab)
        self.alphaBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.alphaBox.setMaximum(100)
        self.alphaBox.setObjectName(_fromUtf8("alphaBox"))
        self.gridLayout.addWidget(self.alphaBox, 1, 4, 1, 1)
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 2, 1, 1)
        self.histCombo = QtGui.QComboBox(self.tab)
        self.histCombo.setStyleSheet(_fromUtf8(""))
        self.histCombo.setObjectName(_fromUtf8("histCombo"))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/DataPlot/icon3.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.histCombo.addItem(icon, _fromUtf8(""))
        self.histCombo.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.histCombo, 2, 3, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 0, 1, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.titleCheck = QtGui.QCheckBox(self.tab_2)
        self.titleCheck.setCheckable(True)
        self.titleCheck.setChecked(False)
        self.titleCheck.setObjectName(_fromUtf8("titleCheck"))
        self.gridLayout_4.addWidget(self.titleCheck, 1, 0, 1, 1)
        self.xAxisCheck = QtGui.QCheckBox(self.tab_2)
        self.xAxisCheck.setObjectName(_fromUtf8("xAxisCheck"))
        self.gridLayout_4.addWidget(self.xAxisCheck, 0, 2, 1, 1)
        self.pltTitle = QtGui.QLineEdit(self.tab_2)
        self.pltTitle.setEnabled(False)
        self.pltTitle.setObjectName(_fromUtf8("pltTitle"))
        self.gridLayout_4.addWidget(self.pltTitle, 1, 1, 1, 1)
        self.legendCheck = QtGui.QCheckBox(self.tab_2)
        self.legendCheck.setEnabled(True)
        self.legendCheck.setChecked(False)
        self.legendCheck.setObjectName(_fromUtf8("legendCheck"))
        self.gridLayout_4.addWidget(self.legendCheck, 0, 0, 1, 1)
        self.yAxisCheck = QtGui.QCheckBox(self.tab_2)
        self.yAxisCheck.setObjectName(_fromUtf8("yAxisCheck"))
        self.gridLayout_4.addWidget(self.yAxisCheck, 1, 2, 1, 1)
        self.xAxisText = QtGui.QLineEdit(self.tab_2)
        self.xAxisText.setEnabled(False)
        self.xAxisText.setObjectName(_fromUtf8("xAxisText"))
        self.gridLayout_4.addWidget(self.xAxisText, 0, 3, 1, 1)
        self.yAxisText = QtGui.QLineEdit(self.tab_2)
        self.yAxisText.setEnabled(False)
        self.yAxisText.setObjectName(_fromUtf8("yAxisText"))
        self.gridLayout_4.addWidget(self.yAxisText, 1, 3, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem1, 1, 0, 1, 2)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.deleteTrace = QtGui.QPushButton(Dialog)
        self.deleteTrace.setGeometry(QtCore.QRect(101, 173, 101, 31))
        self.deleteTrace.setObjectName(_fromUtf8("deleteTrace"))
        self.traceTable = QtGui.QTableWidget(Dialog)
        self.traceTable.setGeometry(QtCore.QRect(10, 210, 734, 189))
        self.traceTable.setMinimumSize(QtCore.QSize(734, 0))
        self.traceTable.setStyleSheet(_fromUtf8(""))
        self.traceTable.setObjectName(_fromUtf8("traceTable"))
        self.traceTable.setColumnCount(5)
        self.traceTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.traceTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.traceTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.traceTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.traceTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.traceTable.setHorizontalHeaderItem(4, item)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QObject.connect(self.LayerCombo, QtCore.SIGNAL(_fromUtf8("layerChanged(QgsMapLayer*)")), self.expField1.setLayer)
        QtCore.QObject.connect(self.alpha, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.alphaBox.setValue)
        QtCore.QObject.connect(self.alphaBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.alpha.setValue)
        QtCore.QObject.connect(self.xAxisCheck, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.xAxisText.setEnabled)
        QtCore.QObject.connect(self.yAxisCheck, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.yAxisText.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.filePath.setText(_translate("Dialog", "Temporary file", None))
        self.addTrace.setText(_translate("Dialog", "Add Trace", None))
        self.browseButton.setText(_translate("Dialog", "...", None))
        self.label_5.setText(_translate("Dialog", "Fill color", None))
        self.label.setText(_translate("Dialog", "Layer", None))
        self.label_2.setText(_translate("Dialog", "Field", None))
        self.label_6.setText(_translate("Dialog", "Transparency", None))
        self.label_3.setText(_translate("Dialog", "Outlier Styling", None))
        self.histCombo.setItemText(0, _translate("Dialog", "overlay", None))
        self.histCombo.setItemText(1, _translate("Dialog", "stack", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Plot Settings", None))
        self.titleCheck.setText(_translate("Dialog", "Plot Title", None))
        self.xAxisCheck.setText(_translate("Dialog", "X Axis Label", None))
        self.pltTitle.setPlaceholderText(_translate("Dialog", "Title", None))
        self.legendCheck.setText(_translate("Dialog", "Show Legend", None))
        self.yAxisCheck.setText(_translate("Dialog", "Y Axis Label", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Layout Customization (optional)", None))
        self.deleteTrace.setText(_translate("Dialog", "Delete Trace", None))
        item = self.traceTable.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Trace ID", None))
        item = self.traceTable.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Layer", None))
        item = self.traceTable.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Field", None))
        item = self.traceTable.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Color", None))
        item = self.traceTable.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Transparecy", None))

from qgis import gui
import resources_rc
