# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Pie.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(719, 304)
        self.gridLayout_3 = QtGui.QGridLayout(Dialog)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.browseButton = QtGui.QToolButton(Dialog)
        self.browseButton.setObjectName(_fromUtf8("browseButton"))
        self.gridLayout_3.addWidget(self.browseButton, 1, 3, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_3.addWidget(self.buttonBox, 2, 1, 1, 2)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 2, 1, 1)
        self.expField1 = gui.QgsFieldExpressionWidget(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.expField1.sizePolicy().hasHeightForWidth())
        self.expField1.setSizePolicy(sizePolicy)
        self.expField1.setObjectName(_fromUtf8("expField1"))
        self.gridLayout.addWidget(self.expField1, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.LayerCombo = gui.QgsMapLayerComboBox(self.tab)
        self.LayerCombo.setObjectName(_fromUtf8("LayerCombo"))
        self.gridLayout.addWidget(self.LayerCombo, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.expField2 = gui.QgsFieldExpressionWidget(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.expField2.sizePolicy().hasHeightForWidth())
        self.expField2.setSizePolicy(sizePolicy)
        self.expField2.setObjectName(_fromUtf8("expField2"))
        self.gridLayout.addWidget(self.expField2, 2, 1, 1, 1)
        self.alpha = QtGui.QSlider(self.tab)
        self.alpha.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.alpha.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.alpha.setMinimum(0)
        self.alpha.setMaximum(100)
        self.alpha.setSingleStep(1)
        self.alpha.setProperty("value", 1)
        self.alpha.setOrientation(QtCore.Qt.Horizontal)
        self.alpha.setInvertedAppearance(False)
        self.alpha.setInvertedControls(False)
        self.alpha.setTickPosition(QtGui.QSlider.TicksAbove)
        self.alpha.setTickInterval(10)
        self.alpha.setObjectName(_fromUtf8("alpha"))
        self.gridLayout.addWidget(self.alpha, 0, 4, 1, 1)
        self.label = QtGui.QLabel(self.tab)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.alphaBox = QtGui.QSpinBox(self.tab)
        self.alphaBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.alphaBox.setMaximum(100)
        self.alphaBox.setObjectName(_fromUtf8("alphaBox"))
        self.gridLayout.addWidget(self.alphaBox, 0, 5, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 0, 1, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.legendCheck = QtGui.QCheckBox(self.tab_2)
        self.legendCheck.setEnabled(True)
        self.legendCheck.setChecked(False)
        self.legendCheck.setObjectName(_fromUtf8("legendCheck"))
        self.gridLayout_4.addWidget(self.legendCheck, 0, 0, 1, 1)
        self.titleCheck = QtGui.QCheckBox(self.tab_2)
        self.titleCheck.setCheckable(True)
        self.titleCheck.setChecked(False)
        self.titleCheck.setObjectName(_fromUtf8("titleCheck"))
        self.gridLayout_4.addWidget(self.titleCheck, 1, 0, 1, 1)
        self.pltTitle = QtGui.QLineEdit(self.tab_2)
        self.pltTitle.setEnabled(False)
        self.pltTitle.setObjectName(_fromUtf8("pltTitle"))
        self.gridLayout_4.addWidget(self.pltTitle, 1, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem1, 1, 0, 1, 2)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 4)
        self.filePath = QtGui.QLineEdit(Dialog)
        self.filePath.setReadOnly(True)
        self.filePath.setPlaceholderText(_fromUtf8(""))
        self.filePath.setObjectName(_fromUtf8("filePath"))
        self.gridLayout_3.addWidget(self.filePath, 1, 1, 1, 2)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QObject.connect(self.LayerCombo, QtCore.SIGNAL(_fromUtf8("layerChanged(QgsMapLayer*)")), self.expField1.setLayer)
        QtCore.QObject.connect(self.LayerCombo, QtCore.SIGNAL(_fromUtf8("layerChanged(QgsMapLayer*)")), self.expField2.setLayer)
        QtCore.QObject.connect(self.alpha, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.alphaBox.setValue)
        QtCore.QObject.connect(self.alphaBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.alpha.setValue)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.browseButton.setText(_translate("Dialog", "...", None))
        self.label_6.setText(_translate("Dialog", "Transparency", None))
        self.label_2.setText(_translate("Dialog", "Label", None))
        self.label_3.setText(_translate("Dialog", "Value", None))
        self.label.setText(_translate("Dialog", "Layer", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Plot Settings", None))
        self.legendCheck.setText(_translate("Dialog", "Show Legend", None))
        self.titleCheck.setText(_translate("Dialog", "Plot Title", None))
        self.pltTitle.setPlaceholderText(_translate("Dialog", "Title", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Layout Customization (optional)", None))
        self.filePath.setText(_translate("Dialog", "Temporary file", None))

from qgis import gui
